export const ATYP = {
  DOMAINNAME: 3,
  IPV4: 1,
  IPV6: 4,
};

export const COMMANDS = {
  BIND: 2,
  CONNECT: 1,
  UDP_ASSOCIATE: 3,
};

export const AUTH_METHODS = {
  LOGIN_PASS: 2,
  GSSAPI: 1,
  NO_ACCEPTABLE_METHODS: 0xff,
  NO_AUTHENTICATION: 0,
};

export const REPLIES = {
  SUCCEEDED: 0,
  GENERAL_FAILURE: 1,
  CONNECTION_NOT_ALLOWED: 2,
  NETWORK_UNREACHABLE: 3,
  HOST_UNREACHABLE: 4,
  CONNECTION_REFUSED: 5,
  TTL_EXPIRED: 6,
  COMMAND_NOT_SUPPORTED: 7,
  ADDRESS_TYPE_NOT_SUPPORTED: 8,
};

export const VERSION = 5;

export const AUTH_REPLIES = {
  GENERAL_FAILURE: 0xff,
  SUCCEEDED: 0,
};

export const AUTH_VERSION = 1;
